services:
  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.5
    restart: unless-stopped

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    container_name: zabbix-snmptraps
    volumes:
      - /zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.2
    ports:
      - "162:1162/udp"
    restart: unless-stopped

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"
      ZBX_ENABLE_SNMP_TRAPS: "true"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.3
    ports:
      - "10051:10051"
    volumes_from:
      - zabbix-snmptraps
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web-nginx-pgsql
    environment:
      ZBX_SERVER_HOST: "zabbix-server-pgsql"
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"
      ZBX_SERVER_NAME: "Zabbix"
      ZBX_SERVER_PORT: "10051"
      ZBX_LOGIN: "Admin"
      ZBX_PASSWORD: "zabbix"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.4
    ports:
      - "443:8443"
      - "80:8080"
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
    restart: unless-stopped

networks:
  zabbix-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20