version: '3.8'

services:
  mongodb:
    image: mongo:6.0.5
    container_name: mongo
    networks:
      graylog_network:
        ipv4_address: 192.18.0.2
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      graylog_network:
        ipv4_address: 192.18.0.3
    restart: unless-stopped
    ports:
      - "9200:9200"

  graylog:
    image: graylog/graylog:6.0
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
      - GRAYLOG_ROOT_PASSWORD_SHA2=a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
      - GRAYLOG_ROOT_USERNAME=admin
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.7.0.32:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://192.18.0.3:9200
      - GRAYLOG_MONGODB_URI=mongodb://192.18.0.2:27017/graylog
    entrypoint: /usr/bin/tini -- /docker-entrypoint.sh
    networks:
      graylog_network:
        ipv4_address: 192.18.0.4
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    volumes:
      - graylog_data:/usr/share/graylog/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      graylog_network:
        ipv4_address: 192.18.0.5
    depends_on:
      - graylog
    restart: unless-stopped

volumes:
  mongo_data:
  es_data:
  graylog_data:

networks:
  graylog_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.0.0/16